on:
  push:
    branches:
      - main/Modrinth/*
      - main/Curseforge/*
  workflow_dispatch:

jobs:
  build-modpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: '26.1.2'
          path: 'the_checkout'
      - name: Build modpack
        run: |
          zip -r Unsimply-Decent.mrpack the_checkout/Modrinth/
          zip -r Unsimply-Decent.zip the_checkout/Curseforge/
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: unsimply-decent-builds
          path:
            - Unsimply-Decent.mrpack
            - Unsimply-Decent.zip
